ci:
  autoupdate_schedule: "monthly"
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_prs: false # Comment "pre-commit.ci autofix" on a PR to trigger

repos:

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "check-merge-conflict"
      - id: "check-yaml"
        # Without --unsafe, !reset in compose YAML triggers error
        args: ["--unsafe"]
      - id: "end-of-file-fixer"
      - id: "mixed-line-ending"
      - id: "trailing-whitespace"
      - id: "check-added-large-files"
        stages: [pre-commit]

  - repo: "https://github.com/psf/black"
    rev: "25.1.0"
    hooks:
      - id: "black"
